// Note: /reference/share-renewal.html contains only a single-character PROV
// lookup (K/L/M/N/P → 'Ontario'). No var FSA = {} was found in the reference
// files. The dataset below is compiled from Canada Post Ontario FSA records.

// ─────────────────────────────────────────────────────────────────────────────
// 1. Ontario FSA → neighbourhood name
// ─────────────────────────────────────────────────────────────────────────────
export const FSA: Record<string, string> = {

  // ── M — City of Toronto ────────────────────────────────────────────────────

  M1B: 'Scarborough West',
  M1C: 'Scarborough Hillside',
  M1E: 'Scarborough Morningside',
  M1G: 'Scarborough Woburn',
  M1H: 'Scarborough Cedarbrae',
  M1J: 'Scarborough Village',
  M1K: 'Scarborough Kennedy Park',
  M1L: 'Clairlea-Birchmount',
  M1M: 'Cliffside-Scarborough',
  M1N: 'Birchcliff-Cliffside',
  M1P: 'Dorset Park',
  M1R: 'Wexford-Maryvale',
  M1S: 'Agincourt South',
  M1T: 'Tam O\'Shanter–Sullivan',
  M1V: 'Agincourt North',
  M1W: 'Steeles East',
  M1X: 'Upper Rouge',

  M2H: 'Hillcrest Village',
  M2J: 'Fairview-Henry Farm',
  M2K: 'Bayview Village',
  M2L: 'York Mills-Windfields',
  M2M: 'Newtonbrook East',
  M2N: 'Willowdale East',
  M2P: 'York Mills West',
  M2R: 'Willowdale West',

  M3A: 'Parkwoods-Donalda',
  M3B: 'Don Mills North',
  M3C: 'Don Mills South',
  M3H: 'Bathurst Manor',
  M3J: 'Downsview-Roding-CFB',
  M3K: 'Humbermede West',
  M3L: 'Downsview East',
  M3M: 'Humbermede',
  M3N: 'Jane and Finch',

  M4A: 'Victoria Village',
  M4B: 'Woodbine Heights-East York',
  M4C: 'Danforth Village-East York',
  M4E: 'East End–Danforth',
  M4G: 'Leaside-Bennington',
  M4H: 'Thorncliffe Park',
  M4J: 'East Toronto-Greenwood',
  M4K: 'Danforth East-Riverdale',
  M4L: 'Greenwood-Coxwell',
  M4M: 'Leslieville-South Riverdale',
  M4N: 'Lawrence Park North',
  M4P: 'Davisville Village',
  M4R: 'North Toronto',
  M4S: 'Davisville North',
  M4T: 'Moore Park-Summerhill',
  M4V: 'Casa Loma',
  M4W: 'Rosedale-Moore Park',
  M4X: 'Cabbagetown-St. James Town',
  M4Y: 'Church-Wellesley Village',

  M5A: 'Regent Park-Distillery District',
  M5B: 'Garden District-St. James Town',
  M5C: 'St. Lawrence Market',
  M5E: 'Harbourfront East-Union Station',
  M5G: 'Discovery District',
  M5H: 'Financial District',
  M5J: 'Harbourfront West-Bathurst Quay',
  M5K: 'Toronto Islands',
  M5L: 'Bay Street Corridor',
  M5M: 'Bedford Park-Nortown',
  M5N: 'Roselawn',
  M5P: 'Forest Hill North',
  M5R: 'Annex-University of Toronto',
  M5S: 'University-Harbord',
  M5T: 'Kensington Market-Chinatown',
  M5V: 'King West-Entertainment District',
  M5W: 'Waterfront (PO Boxes)',
  M5X: 'First Canadian Place',

  M6A: 'Lawrence Heights',
  M6B: 'Glencairn-Englemount',
  M6C: 'Humewood-Cedarvale',
  M6E: 'Caledonia-Fairbank',
  M6G: 'Christie Pits',
  M6H: 'Dovercourt Park',
  M6J: 'Trinity-Bellwoods',
  M6K: 'Parkdale-Roncesvalles East',
  M6L: 'North Park-Maple Leaf',
  M6M: 'Del Ray-Mount Dennis',
  M6N: 'Junction North-Runnymede',
  M6P: 'Junction South-High Park North',
  M6R: 'Roncesvalles-Parkdale',
  M6S: 'Swansea-Runnymede',

  M7A: 'Queen\'s Park',

  M8V: 'Mimico',
  M8W: 'Alderwood-Long Branch',
  M8X: 'Kingsway-Sunnylea',
  M8Y: 'Old Mill-Humber Valley',
  M8Z: 'Etobicoke South',

  M9A: 'Islington-City Centre West',
  M9B: 'West Deane Park-Princess Gardens',
  M9C: 'Markland Wood-Eringate',
  M9L: 'Humber Summit',
  M9M: 'Humberlea-Pelmo Park',
  M9N: 'Weston',
  M9P: 'Westmount-Eatonville',
  M9R: 'Kingsview Village-The Westway',
  M9V: 'Emery-Humbergate',
  M9W: 'Rexdale-Kipling',

  // ── L — Greater Toronto Area ───────────────────────────────────────────────

  // Oshawa / Durham Region
  L1G: 'Oshawa North',
  L1H: 'Oshawa Downtown',
  L1J: 'Oshawa West',
  L1K: 'Oshawa East',
  L1L: 'Oshawa Kedron',
  L1M: 'Whitby North',
  L1N: 'Whitby Downtown',
  L1P: 'Whitby Pringle Creek',
  L1R: 'Whitby Rural',
  L1S: 'Ajax Northwest',
  L1T: 'Ajax-Pickering Village',
  L1V: 'Ajax Northeast',
  L1W: 'Ajax South',
  L1X: 'Pickering Bay Ridges',
  L1Y: 'Pickering Village',
  L1Z: 'Pickering East',

  // Niagara Region
  L2A: 'Fort Erie',
  L2E: 'Niagara Falls North',
  L2G: 'Niagara Falls South',
  L2H: 'Niagara Falls West',
  L2J: 'Niagara Falls East',
  L2M: 'St. Catharines North',
  L2N: 'St. Catharines',
  L2P: 'St. Catharines Grantham',
  L2R: 'St. Catharines Downtown',
  L2S: 'St. Catharines West',
  L2T: 'St. Catharines Ridley',
  L2V: 'St. Catharines Queenston',
  L3B: 'Welland',
  L3C: 'Welland North',
  L3K: 'Port Colborne',
  L3M: 'Grimsby',

  // Markham / York Region
  L3P: 'Markham Village',
  L3R: 'Markham-Thornhill',
  L3S: 'Markham Rouge River',
  L3T: 'Thornhill (Markham)',
  L3X: 'Newmarket East',
  L3Y: 'Newmarket',
  L3Z: 'Bradford',
  L4A: 'Whitchurch-Stouffville',
  L4B: 'Richmond Hill Bayview',
  L4C: 'Richmond Hill',
  L4E: 'Richmond Hill North',
  L4G: 'Aurora',
  L4H: 'Woodbridge',
  L4J: 'Thornhill (Vaughan)',
  L4K: 'Concord-Keele',
  L4L: 'Woodbridge-Islington',
  L4S: 'Richmond Hill East',
  L6A: 'Vaughan Maple',
  L6B: 'Markham Cornell',
  L6C: 'Markham Unionville',
  L6E: 'Markham Greensborough',
  L6G: 'Markham Town Centre',

  // Mississauga / Peel Region
  L4T: 'Mississauga Malton West',
  L4V: 'Mississauga Malton Airport',
  L4W: 'Mississauga Rathwood',
  L4X: 'Mississauga Mavis',
  L4Y: 'Mississauga Dixie',
  L4Z: 'Mississauga Hurontario',
  L5A: 'Mississauga Cooksville',
  L5B: 'Mississauga City Centre',
  L5C: 'Mississauga Central Erin Mills',
  L5E: 'Mississauga Lakeview',
  L5G: 'Mississauga Port Credit',
  L5H: 'Mississauga Mineola',
  L5J: 'Mississauga Clarkson',
  L5K: 'Mississauga Sheridan',
  L5L: 'Mississauga Meadowvale Village',
  L5M: 'Mississauga Churchill Meadows',
  L5N: 'Mississauga Lisgar',
  L5P: 'Mississauga Malton East',
  L5R: 'Mississauga Bramalea South',
  L5S: 'Mississauga Gateway',
  L5T: 'Mississauga Northeast',
  L5V: 'Mississauga Hurontario North',
  L5W: 'Mississauga Meadowvale',

  // Brampton / Peel Region
  L6P: 'Brampton Gore',
  L6R: 'Brampton Sandalwood',
  L6S: 'Brampton Northgate',
  L6T: 'Brampton Bramalea',
  L6V: 'Brampton Centennial',
  L6W: 'Brampton Downtown',
  L6X: 'Brampton East',
  L6Y: 'Brampton Southgate',
  L6Z: 'Brampton Heart Lake',
  L7A: 'Brampton Mount Pleasant',
  L7B: 'King City',
  L7C: 'Caledon Mayfield West',
  L7E: 'Bolton',
  L7G: 'Georgetown',
  L7J: 'Acton',
  L7K: 'Orangeville',

  // Burlington / Halton Region
  L7L: 'Burlington Appleby',
  L7M: 'Burlington Tansley',
  L7N: 'Burlington Roseland',
  L7P: 'Burlington Alton Village',
  L7R: 'Burlington Downtown',
  L7S: 'Burlington Brant Hills',
  L7T: 'Burlington Aldershot',

  // Oakville / Halton Region
  L6H: 'Oakville Glen Abbey',
  L6J: 'Oakville Kerr Village',
  L6K: 'Oakville Bronte',
  L6L: 'Oakville Bronte West',
  L6M: 'Oakville West Oak Trails',
  L9T: 'Milton',

  // Hamilton / Halton
  L8E: 'Stoney Creek',
  L8G: 'Stoney Creek Heritage Green',
  L8H: 'Hamilton East End',
  L8J: 'Hamilton Raleigh-Gershome',
  L8K: 'Hamilton Glenview-Bartonville',
  L8L: 'Hamilton Gibson',
  L8M: 'Hamilton Stipley',
  L8N: 'Hamilton Downtown',
  L8P: 'Hamilton Kirkendall',
  L8R: 'Hamilton Strathcona',
  L8S: 'Hamilton Ainslie Wood-Westdale',
  L8T: 'Hamilton Buchanan',
  L8V: 'Hamilton Lawfield-Yeoville',
  L8W: 'Hamilton McQueston-Rymal',
  L9A: 'Hamilton Mohawk',
  L9B: 'Hamilton Airport',
  L9C: 'Hamilton Westcliffe',
  L9G: 'Waterdown',
  L9H: 'Hamilton Flamborough',
  L9K: 'Hamilton Ancaster South',

  // Barrie / Simcoe County
  L4M: 'Barrie Allandale',
  L4N: 'Barrie',
  L4P: 'Keswick',
  L4R: 'Midland',
  L9R: 'Barrie Allandale North',
  L9S: 'Barrie East',
  L9X: 'Barrie Painswick',
  L9Y: 'Collingwood',
  L9M: 'Penetanguishene',
  L9N: 'Innisfil',
  L9P: 'Uxbridge',

  // ── K — Eastern Ontario ────────────────────────────────────────────────────

  // Ottawa
  K1A: 'Ottawa Parliament Hill',
  K1B: 'Ottawa East-Gloucester',
  K1C: 'Orléans West',
  K1E: 'Orléans East',
  K1G: 'Ottawa Vanier-East',
  K1H: 'Ottawa Alta Vista',
  K1J: 'Ottawa Beacon Hill',
  K1K: 'Ottawa Overbrook',
  K1L: 'Ottawa Lowertown',
  K1M: 'Ottawa Rockcliffe Park',
  K1N: 'Ottawa Sandy Hill',
  K1P: 'Ottawa City Centre',
  K1R: 'Ottawa Centretown West',
  K1S: 'Ottawa Glebe-Old Ottawa South',
  K1T: 'Ottawa Riverside South',
  K1V: 'Ottawa Carleton Heights',
  K1W: 'Ottawa Greely',
  K1X: 'Ottawa Barrhaven South',
  K1Y: 'Ottawa Westboro',
  K1Z: 'Ottawa McKellar Park',
  K2A: 'Ottawa Hintonburg-Mechanicsville',
  K2B: 'Ottawa Britannia',
  K2C: 'Ottawa Carlington',
  K2E: 'Ottawa Nepean North',
  K2G: 'Ottawa Nepean West',
  K2H: 'Ottawa Bells Corners',
  K2J: 'Ottawa Barrhaven',
  K2K: 'Ottawa Kanata North',
  K2L: 'Ottawa Stittsville-Kanata South',
  K2M: 'Ottawa Bridlewood',
  K2P: 'Ottawa Centretown',
  K2R: 'Ottawa Goulbourn',
  K2S: 'Ottawa Stittsville South',
  K2T: 'Ottawa Kanata West',
  K2V: 'Ottawa Richmond',
  K4A: 'Orléans Navan',
  K4B: 'Ottawa Vars',
  K4C: 'Ottawa Cumberland',
  K4K: 'Rockland',
  K4M: 'Manotick',
  K4P: 'Ottawa Metcalfe',
  K4R: 'Ottawa North Gower',

  // Eastern Ontario cities
  K6A: 'Hawkesbury',
  K6H: 'Kingston North',
  K6J: 'Kingston West',
  K6K: 'Kingston East',
  K6T: 'Kingston Rideau Heights',
  K6V: 'Brockville',
  K7A: 'Perth',
  K7C: 'Smiths Falls',
  K7G: 'Gananoque',
  K7H: 'Carleton Place',
  K7K: 'Kingston Downtown',
  K7L: 'Kingston University',
  K7M: 'Kingston East End',
  K7N: 'Kingston West',
  K7P: 'Kingston Southwest',
  K7S: 'Almonte',
  K7V: 'Pembroke',
  K8A: 'Pembroke North',
  K8B: 'Petawawa',
  K8H: 'Bancroft',
  K8N: 'Belleville North',
  K8P: 'Belleville South',
  K8R: 'Trenton South',
  K8V: 'Trenton North',
  K9A: 'Cobourg',
  K9H: 'Peterborough South',
  K9J: 'Peterborough West',
  K9K: 'Peterborough North',
  K9L: 'Peterborough East',
  K9V: 'Lindsay-Kawartha Lakes',

  // ── N — Southwestern Ontario ──────────────────────────────────────────────

  // Guelph
  N1E: 'Guelph East',
  N1G: 'Guelph South',
  N1H: 'Guelph West',
  N1K: 'Guelph Northwest',
  N1L: 'Guelph Southwest',
  N1M: 'Fergus-Centre Wellington',
  N1P: 'Guelph East End',

  // Cambridge
  N1R: 'Cambridge West',
  N1S: 'Cambridge North',
  N1T: 'Cambridge East',

  // Kitchener-Waterloo
  N2A: 'Kitchener East',
  N2B: 'Kitchener Northeast',
  N2C: 'Kitchener Southeast',
  N2E: 'Kitchener West',
  N2G: 'Kitchener Downtown',
  N2H: 'Kitchener North',
  N2J: 'Waterloo South',
  N2K: 'Waterloo East',
  N2L: 'Waterloo West',
  N2M: 'Kitchener Northwest',
  N2N: 'Kitchener Doon',
  N2P: 'Kitchener South',
  N2R: 'Kitchener Southwest',
  N2S: 'Kitchener Fischer-Hallman',
  N2T: 'Waterloo Southwest',
  N2V: 'Waterloo Northwest',

  // Brantford
  N3A: 'Brantford North',
  N3B: 'Brantford Rural',
  N3C: 'Brantford East',
  N3E: 'Brantford Northeast',
  N3H: 'Brantford West',
  N3L: 'Paris-Brant County',
  N3P: 'Brantford South',
  N3R: 'Brantford Downtown',
  N3S: 'Brantford Southeast',
  N3T: 'Brantford Southwest',
  N3Y: 'Simcoe-Norfolk',

  // Other Southwest
  N4B: 'Delhi',
  N4G: 'Tillsonburg',
  N4K: 'Owen Sound',
  N4S: 'Woodstock North',
  N4T: 'Woodstock South',
  N4V: 'Woodstock West',
  N4W: 'Woodstock East',
  N4Z: 'Ingersoll',
  N5A: 'Stratford North',
  N5C: 'Stratford South',
  N5H: 'St. Marys',
  N5R: 'St. Thomas East',
  N5V: 'London East',
  N5W: 'London Carling Heights',
  N5X: 'London Huron Heights',
  N5Y: 'London North',
  N5Z: 'London Southeast',

  // London
  N6A: 'London Downtown',
  N6B: 'London Old East Village',
  N6C: 'London South',
  N6E: 'London Southwest',
  N6G: 'London West',
  N6H: 'London Byron',
  N6J: 'London Lambeth',
  N6K: 'London Highland Hills',
  N6L: 'London Northwest',
  N6M: 'London White Oaks South',
  N6N: 'London White Oaks',
  N6P: 'London Argyle',

  // Sarnia / Windsor / Essex
  N7A: 'Sarnia North',
  N7G: 'Petrolia',
  N7L: 'Sarnia South',
  N7M: 'Strathroy',
  N7S: 'Sarnia East',
  N7T: 'Sarnia West',
  N7V: 'Sarnia Downtown',
  N8A: 'Tecumseh',
  N8H: 'Leamington',
  N8M: 'Leamington East',
  N8N: 'Windsor LaSalle',
  N8P: 'Windsor East',
  N8R: 'Windsor Southeast',
  N8S: 'Windsor Riverside',
  N8T: 'Windsor Walkerville',
  N8V: 'Windsor South',
  N8W: 'Windsor Downtown East',
  N8X: 'Windsor Sandwich',
  N8Y: 'Windsor North',
  N9A: 'Windsor Central',
  N9B: 'Windsor Remington Park',
  N9C: 'Windsor West',
  N9E: 'Windsor South Windsor',
  N9G: 'Windsor Forest Glade',
  N9H: 'Windsor Roseland',
  N9J: 'Windsor Southwest',
  N9K: 'Windsor North',
  N9V: 'Windsor Southeast',

  // ── P — Northern Ontario ──────────────────────────────────────────────────

  P1A: 'North Bay East',
  P1B: 'North Bay West',
  P1C: 'North Bay South',
  P1L: 'Huntsville',
  P1P: 'Huntsville East',
  P2A: 'Parry Sound',
  P2B: 'Parry Sound North',
  P3A: 'Sudbury Northeast',
  P3B: 'Sudbury East',
  P3C: 'Sudbury North',
  P3E: 'Sudbury New Sudbury',
  P3G: 'Sudbury South',
  P3L: 'Sudbury West',
  P3N: 'Sudbury Rural South',
  P4N: 'Timmins North',
  P4P: 'Timmins South',
  P5A: 'Sault Ste. Marie East',
  P5E: 'Sault Ste. Marie West',
  P6A: 'Sault Ste. Marie Central',
  P6B: 'Sault Ste. Marie South',
  P7A: 'Thunder Bay North',
  P7B: 'Thunder Bay East',
  P7C: 'Thunder Bay Current River',
  P7E: 'Thunder Bay South',
  P7G: 'Thunder Bay Rural',
  P7J: 'Thunder Bay West',
  P7K: 'Thunder Bay Westfort',
  P7L: 'Thunder Bay Intercity',
  P8N: 'Dryden',
  P8T: 'Kenora',
  P9A: 'Fort Frances',
  P9N: 'Kenora North',
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. Non-Ontario province fallback (single-letter prefix)
// ─────────────────────────────────────────────────────────────────────────────
export const PROV_FALLBACK: Record<string, string> = {
  A: 'Newfoundland & Labrador',
  B: 'Nova Scotia',
  C: 'Prince Edward Island',
  E: 'New Brunswick',
  G: 'Quebec',
  H: 'Quebec',
  J: 'Quebec',
  R: 'Manitoba',
  S: 'Saskatchewan',
  T: 'Alberta',
  V: 'British Columbia',
  X: 'NWT / Nunavut',
  Y: 'Yukon',
}

// Ontario FSA prefixes — not in PROV_FALLBACK because FSA covers them
const ONTARIO = new Set(['K', 'L', 'M', 'N', 'P'])

// ─────────────────────────────────────────────────────────────────────────────
// 3. getAreaLabel — matches the logic of onFsa() in /reference/share-renewal.html,
//    extended with FSA-level precision at 2 and 3 characters.
// ─────────────────────────────────────────────────────────────────────────────
export function getAreaLabel(fsa: string): string {
  const v = fsa.toUpperCase()

  if (v.length === 0) return ''

  // 1 char — province / territory name
  if (v.length === 1) {
    if (ONTARIO.has(v)) return 'Ontario'
    return PROV_FALLBACK[v] ?? ''
  }

  // 2 chars — find first matching FSA, return its name with ellipsis
  if (v.length === 2) {
    const match = Object.keys(FSA).find(k => k.startsWith(v))
    if (match) return FSA[match] + '…'
    if (ONTARIO.has(v.charAt(0))) return 'Ontario'
    return PROV_FALLBACK[v.charAt(0)] ?? ''
  }

  // 3 chars — exact FSA lookup or province fallback
  const key = v.slice(0, 3)
  if (FSA[key]) return FSA[key]
  if (ONTARIO.has(key.charAt(0))) return 'Ontario'
  return PROV_FALLBACK[key.charAt(0)] ?? ''
}
